### ISSUE TITLE
429 (Too Many Requests) error message when opening messages page

### ISSUE THREAD

**Issue by rleitan** [mozilla-it/discourse-infra#32]
[Environment]:
Ubuntu 16.04 x64, Windows 10 - Firefox,Chrome

[Precondition]:
Create 2 posts and send some messages

[STR]:
1.Open https://discourse-staging.itsre-apps.mozit.cloud/u/rleitan/messages

[Actual result]:
The page is correctly displayed

Console error: _ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:9851 POST https://discourse-staging.itsre-apps.mozit.cloud/message-bus/acfcb4121c1d45caa060d17c45c307d7/poll 429 (Too Many Requests)

**Comment by the-smooth-operator** [comment]
Thanks @rleitan for finding this. 

The NGINX embedded into Discourse was applying rate limiting to traffic which should not have rate limited. The problem is that it was using the IP of the ingress-controller (nginx in front of him) so all connections appeared to be coming from the same IP.

We have disabled rate limiting in the discourse container level, and instead applied it to the ingress-controller in front of it. This gives us better control and removes tasks to the discourse container.

See https://github.com/mozilla/discourse.mozilla.org/pull/15

**Comment by the-smooth-operator** [comment]
Can you check if you still experience this behavior? @rleitan

**Comment by rleitan** [comment]
I cannot reproduce this anymore! Closing this bug
